###########################
# Default Input
###########################
size: [224, 224]
# Mode of interpolation in resize functions
interpolation: "bilinear"
# For available choices please refer to transforms.py
transforms: ["normalize"]
# If True, tfm_train and tfm_test will be None
no_transform: False
# Mean and std (default: ImageNet)
pixel_mean: [0.485, 0.456, 0.406]
pixel_std: [0.229, 0.224, 0.225]
# Random crop
crop_padding: 4
# Random resized crop
rrcrop_scale: [0.08, 1.0]